// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbfYUZBDbo5OzP-CIZTdby0XPaWyqBaWM',
    appId: '1:38854558303:web:b3e09cfefd595b20f411ea',
    messagingSenderId: '38854558303',
    projectId: 'drip-0556',
    authDomain: 'drip-0556.firebaseapp.com',
    storageBucket: 'drip-0556.appspot.com',
    measurementId: 'G-SGCP72G0DC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC2YtGqM-Pays6BaLh2-NQA2Ae8lSFCfQ',
    appId: '1:38854558303:android:5334f292e3ac4a9cf411ea',
    messagingSenderId: '38854558303',
    projectId: 'drip-0556',
    storageBucket: 'drip-0556.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrJMG2v7pxPC1INZVadSu9LbXRxJc3Y_M',
    appId: '1:38854558303:ios:3732e5582554df5af411ea',
    messagingSenderId: '38854558303',
    projectId: 'drip-0556',
    storageBucket: 'drip-0556.appspot.com',
    androidClientId: '38854558303-lpj1dpa3g6t1abcvnvb2p23trq065uuo.apps.googleusercontent.com',
    iosClientId: '38854558303-pshjp3eop3rtt7sis0aak0rgqv3n3j9t.apps.googleusercontent.com',
    iosBundleId: 'com.example.drip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrJMG2v7pxPC1INZVadSu9LbXRxJc3Y_M',
    appId: '1:38854558303:ios:a864634a389a6948f411ea',
    messagingSenderId: '38854558303',
    projectId: 'drip-0556',
    storageBucket: 'drip-0556.appspot.com',
    androidClientId: '38854558303-lpj1dpa3g6t1abcvnvb2p23trq065uuo.apps.googleusercontent.com',
    iosClientId: '38854558303-q27c6f4rcl68s0va7vnsg01aah97q90k.apps.googleusercontent.com',
    iosBundleId: 'com.example.drip.RunnerTests',
  );
}
